version: "3.3"

networks:
  inception-network:
    driver: bridge
    name: inception-network
  
services:
  nginx:
    build: srcs/nginx/.
    volumes:
            - volume_wordpress:/var/www/html:rw
            - volume_mariadb:/var/lib/mysql:rw
    depends_on:
      - wordpress
    container_name: container_nginx
    restart: unless-stopped
    ports:
      - 443:443
    networks:
      - inception-network

  mariadb:
    build: srcs/mariadb/.
    volumes:
      - volume_mariadb:/var/lib/mysql
    container_name: container_mariadb
    restart: unless-stopped
    networks:
      - inception-network

  wordpress:
    build: srcs/wordpress/.
    volumes:
            - volume_wordpress:/var/www/html:rw
    depends_on:
      - mariadb
    container_name: container_wordpress
    restart: unless-stopped
    networks:
      - inception-network

volumes:
  volume_wordpress:
    name: volume_wordpress
    driver: local
    driver_opts:
      type: none
      device: /home/ade-temm/data/
      o: bind

  volume_mariadb:
    name: volume_mariadb
    driver: local
    driver_opts:
      type: none
      device: /home/ade-temm/data/
      o: bind
