version: "3.3"

services:
  nginx:
    build: srcs/nginx/.
    container_name: container_nginx
    restart: unless-stopped
    ports:
      - 443:443
    networks:
      - inception-network

  mariadb:
    build: srcs/mariadb/.
    volumes:
      - volume_mariadb:/var/lib/mysql
    container_name: container_mariadb
    restart: unless-stopped
    networks:
      - inception-network

  wordpress:
    build: srcs/wordpress/.
    volumes:
      - volume_wordpress:/var/www/html
    container_name: container_wordpress
    restart: unless-stopped
    networks:
      - inception-network

networks:
  inception-network:
    driver: bridge
    name: inception-network

volumes:
  volume_wordpress:
    name: volume_wordpress
    driver: local
    driver_opts:
      type: volume
      device: /home/alex2tsudo/data/volume_wordpress

  volume_mariadb:
    name: volume_mariadb
    driver: local
    driver_opts:
      type: volume
      device: /home/alex2tsudo/data/volume_mariadb