version: "3.3"
services:
  nginx:
    build: srcs/nginx/.
    container_name: container_nginx
    restart: always
    ports:
      - 443:443
  mariadb:
    build: srcs/mariadb/.
    container_name: container_mariadb
    restart: always